import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/providers/QueryProvider";
import { toastStyle } from "@/styles/toast";
import NextAuthSessionProvider from "@/providers/SessionProvider";
import { ChatProvider } from "@/context/chat/ChatProvider";
import { AuthProvider } from "@/context/auth/AuthProvider";
import AnimatedGradientBackground from "@/components/animatedBackground/AnimatedBackground";
import TopProgressBar from "@/components/ui/TopProgressBar";
import NetworkStatus from "@/components/NetworkStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `} suppressHydrationWarning>
        <NextAuthSessionProvider>
          <QueryProvider>
            <AuthProvider>
              <ChatProvider>
                <TopProgressBar/>
                <NetworkStatus/>
                <Toaster toastOptions={toastStyle} />
                <AnimatedGradientBackground />
                {children}
              </ChatProvider>
            </AuthProvider>
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
